/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChessRank = { 'A' : null } |
  { 'B' : null } |
  { 'C' : null } |
  { 'D' : null } |
  { 'E' : null } |
  { 'S' : null } |
  { 'National' : null } |
  { 'Monarch' : null } |
  { 'Absolute' : null };
export type Player = { 'anonymous' : null } |
  {
    'named' : {
      'xp' : bigint,
      'name' : string,
      'rank' : ChessRank,
      'level' : bigint,
      'skills' : Skills,
    }
  };
export interface Skills {
  'calculation' : bigint,
  'timeManagement' : bigint,
  'endgameTechnique' : bigint,
  'openingKnowledge' : bigint,
  'patternRecognition' : bigint,
}
export interface _SERVICE {
  'createPlayer' : ActorMethod<[string], string>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getPlayer' : ActorMethod<[string], Player>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];