/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChessRank = IDL.Variant({
  'A' : IDL.Null,
  'B' : IDL.Null,
  'C' : IDL.Null,
  'D' : IDL.Null,
  'E' : IDL.Null,
  'S' : IDL.Null,
  'National' : IDL.Null,
  'Monarch' : IDL.Null,
  'Absolute' : IDL.Null,
});
export const Skills = IDL.Record({
  'calculation' : IDL.Nat,
  'timeManagement' : IDL.Nat,
  'endgameTechnique' : IDL.Nat,
  'openingKnowledge' : IDL.Nat,
  'patternRecognition' : IDL.Nat,
});
export const Player = IDL.Variant({
  'anonymous' : IDL.Null,
  'named' : IDL.Record({
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'rank' : ChessRank,
    'level' : IDL.Nat,
    'skills' : Skills,
  }),
});

export const idlService = IDL.Service({
  'createPlayer' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getPlayer' : IDL.Func([IDL.Text], [Player], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChessRank = IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
    'D' : IDL.Null,
    'E' : IDL.Null,
    'S' : IDL.Null,
    'National' : IDL.Null,
    'Monarch' : IDL.Null,
    'Absolute' : IDL.Null,
  });
  const Skills = IDL.Record({
    'calculation' : IDL.Nat,
    'timeManagement' : IDL.Nat,
    'endgameTechnique' : IDL.Nat,
    'openingKnowledge' : IDL.Nat,
    'patternRecognition' : IDL.Nat,
  });
  const Player = IDL.Variant({
    'anonymous' : IDL.Null,
    'named' : IDL.Record({
      'xp' : IDL.Nat,
      'name' : IDL.Text,
      'rank' : ChessRank,
      'level' : IDL.Nat,
      'skills' : Skills,
    }),
  });
  
  return IDL.Service({
    'createPlayer' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getPlayer' : IDL.Func([IDL.Text], [Player], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };