/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Player = {
    __kind__: "anonymous";
    anonymous: null;
} | {
    __kind__: "named";
    named: {
        xp: bigint;
        name: string;
        rank: ChessRank;
        level: bigint;
        skills: Skills;
    };
};
export interface Skills {
    calculation: bigint;
    timeManagement: bigint;
    endgameTechnique: bigint;
    openingKnowledge: bigint;
    patternRecognition: bigint;
}
export enum ChessRank {
    A = "A",
    B = "B",
    C = "C",
    D = "D",
    E = "E",
    S = "S",
    National = "National",
    Monarch = "Monarch",
    Absolute = "Absolute"
}
export interface backendInterface {
    createPlayer(name: string): Promise<string>;
    getAllPlayers(): Promise<Array<Player>>;
    getPlayer(playerId: string): Promise<Player>;
}
import type { ChessRank as _ChessRank, Player as _Player, Skills as _Skills } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPlayer(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0);
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_Player_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_Player_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChessRank_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChessRank): ChessRank {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    name: string;
    rank: _ChessRank;
    level: bigint;
    skills: _Skills;
}): {
    xp: bigint;
    name: string;
    rank: ChessRank;
    level: bigint;
    skills: Skills;
} {
    return {
        xp: value.xp,
        name: value.name,
        rank: from_candid_ChessRank_n5(_uploadFile, _downloadFile, value.rank),
        level: value.level,
        skills: value.skills
    };
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    anonymous: null;
} | {
    named: {
        xp: bigint;
        name: string;
        rank: _ChessRank;
        level: bigint;
        skills: _Skills;
    };
}): {
    __kind__: "anonymous";
    anonymous: null;
} | {
    __kind__: "named";
    named: {
        xp: bigint;
        name: string;
        rank: ChessRank;
        level: bigint;
        skills: Skills;
    };
} {
    return "anonymous" in value ? {
        __kind__: "anonymous",
        anonymous: value.anonymous
    } : "named" in value ? {
        __kind__: "named",
        named: from_candid_record_n4(_uploadFile, _downloadFile, value.named)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    A: null;
} | {
    B: null;
} | {
    C: null;
} | {
    D: null;
} | {
    E: null;
} | {
    S: null;
} | {
    National: null;
} | {
    Monarch: null;
} | {
    Absolute: null;
}): ChessRank {
    return "A" in value ? ChessRank.A : "B" in value ? ChessRank.B : "C" in value ? ChessRank.C : "D" in value ? ChessRank.D : "E" in value ? ChessRank.E : "S" in value ? ChessRank.S : "National" in value ? ChessRank.National : "Monarch" in value ? ChessRank.Monarch : "Absolute" in value ? ChessRank.Absolute : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
